---
title: "Analyzing The Influence of Biological Factors vs. Lifestyle Habits on Stroke Victims"
author: "Group 4"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: html_document
---

Biological Factors

| | |
| --- | --- |
| gender | categorical |
| age | numeric |
| hypertension | categorical |
| heart_disease | categorical |
| avg_glucose_level |
| bmi | categorical |


Lifestyle Habits:

- ever_married
- work_type
- Residence_type
- smoking_status 

```{r setup, echo=F}
set.seed(10);
library(ggplot2);
library(dplyr);
library(knitr);
library(car);
library(ROCR);
library(corrplot); #correlation heat map

load_stroke_data <- function(path) {
    read.csv(path, header = T, na.strings = "N/A");
}

prep_stroke_data <- function(stroke_data) {
    stroke_data <- na.omit(stroke_data);
    stroke_data <- stroke_data[-which(stroke_data$gender == "Other"), ];
    stroke_data$smoking_status <- factor(
        stroke_data$smoking_status,
        levels = c(
            'never smoked',
            'formerly smoked',
            'smokes'
        )
    );
    stroke_data$work_type <- factor(
        stroke_data$work_type,
        levels = c(
            'Never_worked',
            'Private',
            'Self-employed',
            'Govt_job',
            'children'
        )
    );
    
    return(stroke_data);
}

split_stroke_data <- function(stroke_data, training_proportion) {
    n <- nrow(stroke_data);
    num_training <- n * training_proportion;
    training_i <- sample.int(n, num_training);
    
    list(
        training = stroke_data[training_i, ],
        test = stroke_data[-training_i, ]
    );
}

stroke <- load_stroke_data("healthcare-dataset-stroke-data.csv") |> 
    prep_stroke_data() |> 
    split_stroke_data(training_proportion = 0.8);
```






### Restricted Model
```{r eda-restricted, echo=F}
restricted_model <- glm(
    stroke ~ 
        hypertension * age + 
        age * avg_glucose_level + 
        ever_married,
    data = stroke$training
);
summary(restricted_model);
```



Functions:
```{r}
model_accuracy <- function(model_pred){
  accuracy <- mean(model_pred == stroke$training$stroke)
  return(paste("Accuracy =", round(accuracy, 4)))
}

roc <- function(model_pred){
  roc_pred <- prediction(model_pred, stroke$training$stroke)
  roc_perf <- performance(roc_pred, measure = "tpr", x.measure = "fpr")
  
  auc <- performance(roc_pred, measure = "auc")
  auc <- auc@y.values[[1]]
   
  # Plotting
  plot(roc_perf, main = "ROC CURVE", col = "blue", lwd = 1.5)
  legend(.6, .4, round(auc, 4), title = "AUC", cex = 1)
}

confusion_matrix <- function(model_pred) {
  table(model_pred, stroke$training$stroke)
}
```

#ROC Curve:
```{r}
log_pred <- predict(restricted_model, stroke$training, type = "response")
```


```{r}
roc(log_pred)
```
Using Training data to determine Threshold:
```{r}
log_pred_2 <- ifelse(log_pred >= 0.05, 1, 0)
model_accuracy(log_pred_2)
confusion_matrix(log_pred_2)
```

Now for Test data:
```{r}
model_accuracy_test <- function(model_pred){
  accuracy <- mean(model_pred == stroke$test$stroke)
  return(paste("Accuracy =", round(accuracy, 4)))
}

confusion_matrix_test <- function(model_pred) {
  table(model_pred, stroke$test$stroke)
}
```



```{r}
log_pred_test <- predict(restricted_model, stroke$test, type = "response")
log_pred_class_test <- ifelse(log_pred_test >= 0.05, 1, 0)
model_accuracy_test(log_pred_class_test)
confusion_matrix_test(log_pred_class_test)
```
